// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO platform.alert_rule (
  tenant_id, name, enabled, kind, scope_kind, scope_id, window_days, webhook_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, name, enabled, kind, scope_kind, scope_id, window_days, webhook_url, created_at, updated_at
`

type CreateAlertRuleParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	Name       string      `json:"name"`
	Enabled    bool        `json:"enabled"`
	Kind       string      `json:"kind"`
	ScopeKind  string      `json:"scope_kind"`
	ScopeID    pgtype.UUID `json:"scope_id"`
	WindowDays int32       `json:"window_days"`
	WebhookUrl string      `json:"webhook_url"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (PlatformAlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.TenantID,
		arg.Name,
		arg.Enabled,
		arg.Kind,
		arg.ScopeKind,
		arg.ScopeID,
		arg.WindowDays,
		arg.WebhookUrl,
	)
	var i PlatformAlertRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Enabled,
		&i.Kind,
		&i.ScopeKind,
		&i.ScopeID,
		&i.WindowDays,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM platform.alert_rule WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, id)
	return err
}

const findMatchingAlertRules = `-- name: FindMatchingAlertRules :many
SELECT id, tenant_id, name, enabled, kind, scope_kind, scope_id, window_days, webhook_url, created_at, updated_at FROM platform.alert_rule
WHERE tenant_id = $1
  AND enabled = TRUE
  AND scope_kind = $2
  AND window_days = $3
  AND (scope_id IS NULL OR scope_id = $4)
`

type FindMatchingAlertRulesParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	ScopeKind  string      `json:"scope_kind"`
	WindowDays int32       `json:"window_days"`
	ScopeID    pgtype.UUID `json:"scope_id"`
}

// Localiza regras habilitadas que cobrem um scope+window específico.
// scope_id NULL na regra = matches all scopes do tipo dentro do tenant.
func (q *Queries) FindMatchingAlertRules(ctx context.Context, arg FindMatchingAlertRulesParams) ([]PlatformAlertRule, error) {
	rows, err := q.db.Query(ctx, findMatchingAlertRules,
		arg.TenantID,
		arg.ScopeKind,
		arg.WindowDays,
		arg.ScopeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAlertRule{}
	for rows.Next() {
		var i PlatformAlertRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Enabled,
			&i.Kind,
			&i.ScopeKind,
			&i.ScopeID,
			&i.WindowDays,
			&i.WebhookUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertEvent = `-- name: GetAlertEvent :one
SELECT id, rule_id, tenant_id, fired_at, scope_kind, scope_id, previous_tier, current_tier, payload, delivery_status, http_status, last_error, delivered_at FROM platform.alert_event WHERE id = $1
`

func (q *Queries) GetAlertEvent(ctx context.Context, id uuid.UUID) (PlatformAlertEvent, error) {
	row := q.db.QueryRow(ctx, getAlertEvent, id)
	var i PlatformAlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.TenantID,
		&i.FiredAt,
		&i.ScopeKind,
		&i.ScopeID,
		&i.PreviousTier,
		&i.CurrentTier,
		&i.Payload,
		&i.DeliveryStatus,
		&i.HttpStatus,
		&i.LastError,
		&i.DeliveredAt,
	)
	return i, err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, tenant_id, name, enabled, kind, scope_kind, scope_id, window_days, webhook_url, created_at, updated_at FROM platform.alert_rule WHERE id = $1
`

func (q *Queries) GetAlertRule(ctx context.Context, id uuid.UUID) (PlatformAlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, id)
	var i PlatformAlertRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Enabled,
		&i.Kind,
		&i.ScopeKind,
		&i.ScopeID,
		&i.WindowDays,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlertEvent = `-- name: InsertAlertEvent :one
INSERT INTO platform.alert_event (
  rule_id, tenant_id, scope_kind, scope_id,
  previous_tier, current_tier, payload
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, rule_id, tenant_id, fired_at, scope_kind, scope_id, previous_tier, current_tier, payload, delivery_status, http_status, last_error, delivered_at
`

type InsertAlertEventParams struct {
	RuleID       uuid.UUID `json:"rule_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	ScopeKind    string    `json:"scope_kind"`
	ScopeID      uuid.UUID `json:"scope_id"`
	PreviousTier *string   `json:"previous_tier"`
	CurrentTier  string    `json:"current_tier"`
	Payload      []byte    `json:"payload"`
}

func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (PlatformAlertEvent, error) {
	row := q.db.QueryRow(ctx, insertAlertEvent,
		arg.RuleID,
		arg.TenantID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.PreviousTier,
		arg.CurrentTier,
		arg.Payload,
	)
	var i PlatformAlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.TenantID,
		&i.FiredAt,
		&i.ScopeKind,
		&i.ScopeID,
		&i.PreviousTier,
		&i.CurrentTier,
		&i.Payload,
		&i.DeliveryStatus,
		&i.HttpStatus,
		&i.LastError,
		&i.DeliveredAt,
	)
	return i, err
}

const listAlertEventsByRule = `-- name: ListAlertEventsByRule :many
SELECT id, rule_id, tenant_id, fired_at, scope_kind, scope_id, previous_tier, current_tier, payload, delivery_status, http_status, last_error, delivered_at FROM platform.alert_event
WHERE rule_id = $1
ORDER BY fired_at DESC
LIMIT $2
`

type ListAlertEventsByRuleParams struct {
	RuleID uuid.UUID `json:"rule_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListAlertEventsByRule(ctx context.Context, arg ListAlertEventsByRuleParams) ([]PlatformAlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEventsByRule, arg.RuleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAlertEvent{}
	for rows.Next() {
		var i PlatformAlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TenantID,
			&i.FiredAt,
			&i.ScopeKind,
			&i.ScopeID,
			&i.PreviousTier,
			&i.CurrentTier,
			&i.Payload,
			&i.DeliveryStatus,
			&i.HttpStatus,
			&i.LastError,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRulesByTenant = `-- name: ListAlertRulesByTenant :many
SELECT id, tenant_id, name, enabled, kind, scope_kind, scope_id, window_days, webhook_url, created_at, updated_at FROM platform.alert_rule
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAlertRulesByTenant(ctx context.Context, tenantID uuid.UUID) ([]PlatformAlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRulesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAlertRule{}
	for rows.Next() {
		var i PlatformAlertRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Enabled,
			&i.Kind,
			&i.ScopeKind,
			&i.ScopeID,
			&i.WindowDays,
			&i.WebhookUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAlertEvents = `-- name: ListRecentAlertEvents :many
SELECT id, rule_id, tenant_id, fired_at, scope_kind, scope_id, previous_tier, current_tier, payload, delivery_status, http_status, last_error, delivered_at FROM platform.alert_event
WHERE tenant_id = $1
ORDER BY fired_at DESC
LIMIT $2
`

type ListRecentAlertEventsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListRecentAlertEvents(ctx context.Context, arg ListRecentAlertEventsParams) ([]PlatformAlertEvent, error) {
	rows, err := q.db.Query(ctx, listRecentAlertEvents, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAlertEvent{}
	for rows.Next() {
		var i PlatformAlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TenantID,
			&i.FiredAt,
			&i.ScopeKind,
			&i.ScopeID,
			&i.PreviousTier,
			&i.CurrentTier,
			&i.Payload,
			&i.DeliveryStatus,
			&i.HttpStatus,
			&i.LastError,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertEventDelivered = `-- name: MarkAlertEventDelivered :exec
UPDATE platform.alert_event
SET delivery_status = 'delivered',
    http_status     = $2,
    delivered_at    = now(),
    last_error      = NULL
WHERE id = $1
`

type MarkAlertEventDeliveredParams struct {
	ID         uuid.UUID `json:"id"`
	HttpStatus *int32    `json:"http_status"`
}

func (q *Queries) MarkAlertEventDelivered(ctx context.Context, arg MarkAlertEventDeliveredParams) error {
	_, err := q.db.Exec(ctx, markAlertEventDelivered, arg.ID, arg.HttpStatus)
	return err
}

const markAlertEventFailed = `-- name: MarkAlertEventFailed :exec
UPDATE platform.alert_event
SET delivery_status = 'failed',
    http_status     = $2,
    last_error      = $3
WHERE id = $1
`

type MarkAlertEventFailedParams struct {
	ID         uuid.UUID `json:"id"`
	HttpStatus *int32    `json:"http_status"`
	LastError  *string   `json:"last_error"`
}

func (q *Queries) MarkAlertEventFailed(ctx context.Context, arg MarkAlertEventFailedParams) error {
	_, err := q.db.Exec(ctx, markAlertEventFailed, arg.ID, arg.HttpStatus, arg.LastError)
	return err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE platform.alert_rule
SET name        = COALESCE($1, name),
    enabled     = COALESCE($2, enabled),
    kind        = COALESCE($3, kind),
    scope_kind  = COALESCE($4, scope_kind),
    scope_id    = COALESCE($5, scope_id),
    window_days = COALESCE($6, window_days),
    webhook_url = COALESCE($7, webhook_url),
    updated_at  = now()
WHERE id = $8
RETURNING id, tenant_id, name, enabled, kind, scope_kind, scope_id, window_days, webhook_url, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	Name       *string     `json:"name"`
	Enabled    *bool       `json:"enabled"`
	Kind       *string     `json:"kind"`
	ScopeKind  *string     `json:"scope_kind"`
	ScopeID    pgtype.UUID `json:"scope_id"`
	WindowDays *int32      `json:"window_days"`
	WebhookUrl *string     `json:"webhook_url"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (PlatformAlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.Name,
		arg.Enabled,
		arg.Kind,
		arg.ScopeKind,
		arg.ScopeID,
		arg.WindowDays,
		arg.WebhookUrl,
		arg.ID,
	)
	var i PlatformAlertRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Enabled,
		&i.Kind,
		&i.ScopeKind,
		&i.ScopeID,
		&i.WindowDays,
		&i.WebhookUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
