// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classification_thresholds.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getClassificationThreshold = `-- name: GetClassificationThreshold :one
SELECT tenant_id, config FROM platform.classification_threshold WHERE tenant_id = $1
`

func (q *Queries) GetClassificationThreshold(ctx context.Context, tenantID uuid.UUID) (PlatformClassificationThreshold, error) {
	row := q.db.QueryRow(ctx, getClassificationThreshold, tenantID)
	var i PlatformClassificationThreshold
	err := row.Scan(&i.TenantID, &i.Config)
	return i, err
}

const upsertClassificationThreshold = `-- name: UpsertClassificationThreshold :one
INSERT INTO platform.classification_threshold (tenant_id, config)
VALUES ($1, $2)
ON CONFLICT (tenant_id) DO UPDATE
  SET config = EXCLUDED.config
RETURNING tenant_id, config
`

type UpsertClassificationThresholdParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Config   []byte    `json:"config"`
}

func (q *Queries) UpsertClassificationThreshold(ctx context.Context, arg UpsertClassificationThresholdParams) (PlatformClassificationThreshold, error) {
	row := q.db.QueryRow(ctx, upsertClassificationThreshold, arg.TenantID, arg.Config)
	var i PlatformClassificationThreshold
	err := row.Scan(&i.TenantID, &i.Config)
	return i, err
}
