// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSuccessfulProductionDeploymentsInWindow = `-- name: CountSuccessfulProductionDeploymentsInWindow :one
SELECT COUNT(*) AS deploy_count
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
WHERE d.project_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
`

type CountSuccessfulProductionDeploymentsInWindowParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CountSuccessfulProductionDeploymentsInWindow(ctx context.Context, arg CountSuccessfulProductionDeploymentsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulProductionDeploymentsInWindow, arg.ProjectID, arg.FinishedAt)
	var deploy_count int64
	err := row.Scan(&deploy_count)
	return deploy_count, err
}

const upsertDeployment = `-- name: UpsertDeployment :one
INSERT INTO platform.deployment (
  project_id, environment_id, external_id, sha, ref, status,
  triggered_by, started_at, finished_at, is_rollback, raw_payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (project_id, external_id) DO UPDATE
  SET status = EXCLUDED.status,
      finished_at = EXCLUDED.finished_at,
      raw_payload = EXCLUDED.raw_payload
RETURNING id, project_id, environment_id, external_id, sha, ref, status, triggered_by, started_at, finished_at, is_rollback, raw_payload
`

type UpsertDeploymentParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	EnvironmentID uuid.UUID          `json:"environment_id"`
	ExternalID    string             `json:"external_id"`
	Sha           string             `json:"sha"`
	Ref           *string            `json:"ref"`
	Status        string             `json:"status"`
	TriggeredBy   *string            `json:"triggered_by"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	IsRollback    bool               `json:"is_rollback"`
	RawPayload    []byte             `json:"raw_payload"`
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (PlatformDeployment, error) {
	row := q.db.QueryRow(ctx, upsertDeployment,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ExternalID,
		arg.Sha,
		arg.Ref,
		arg.Status,
		arg.TriggeredBy,
		arg.StartedAt,
		arg.FinishedAt,
		arg.IsRollback,
		arg.RawPayload,
	)
	var i PlatformDeployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.Sha,
		&i.Ref,
		&i.Status,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.IsRollback,
		&i.RawPayload,
	)
	return i, err
}
