// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_incident_links.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findDeploymentForIncident = `-- name: FindDeploymentForIncident :one
SELECT d.id
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
WHERE d.project_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at IS NOT NULL
  AND d.finished_at <= $2
  AND d.finished_at >= $3
ORDER BY d.finished_at DESC
LIMIT 1
`

type FindDeploymentForIncidentParams struct {
	ProjectID         uuid.UUID          `json:"project_id"`
	IncidentCreatedAt pgtype.Timestamptz `json:"incident_created_at"`
	LookbackFloor     pgtype.Timestamptz `json:"lookback_floor"`
}

// Acha o deployment de produção bem-sucedido mais recente do projeto cujo
// finished_at está em (incident.created_at - lookback, incident.created_at].
// Usado pelo time-window linking de CFR (default lookback = 24h).
func (q *Queries) FindDeploymentForIncident(ctx context.Context, arg FindDeploymentForIncidentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDeploymentForIncident, arg.ProjectID, arg.IncidentCreatedAt, arg.LookbackFloor)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertDeploymentIncidentLink = `-- name: UpsertDeploymentIncidentLink :exec
INSERT INTO platform.deployment_incident_link (deployment_id, incident_id, link_reason)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type UpsertDeploymentIncidentLinkParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	IncidentID   uuid.UUID `json:"incident_id"`
	LinkReason   string    `json:"link_reason"`
}

func (q *Queries) UpsertDeploymentIncidentLink(ctx context.Context, arg UpsertDeploymentIncidentLinkParams) error {
	_, err := q.db.Exec(ctx, upsertDeploymentIncidentLink, arg.DeploymentID, arg.IncidentID, arg.LinkReason)
	return err
}
