// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changeFailureRateInWindow = `-- name: ChangeFailureRateInWindow :one
SELECT
  COALESCE(
    CAST(SUM(CASE WHEN linked_count > 0 THEN 1 ELSE 0 END) AS numeric)
      / NULLIF(COUNT(*), 0),
    0
  ) AS cfr,
  COUNT(*) AS sample_size
FROM (
  SELECT d.id, COUNT(dil.incident_id) AS linked_count
  FROM platform.deployment d
  JOIN platform.environment e ON e.id = d.environment_id
  LEFT JOIN platform.deployment_incident_link dil ON dil.deployment_id = d.id
  WHERE d.project_id = $1
    AND e.is_production
    AND d.status = 'success'
    AND d.finished_at >= $2
  GROUP BY d.id
) AS by_deploy
`

type ChangeFailureRateInWindowParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	FinishedSince pgtype.Timestamptz `json:"finished_since"`
}

type ChangeFailureRateInWindowRow struct {
	Cfr        interface{} `json:"cfr"`
	SampleSize int64       `json:"sample_size"`
}

// (deploys com >= 1 incident vinculado) / (deploys de produção bem-sucedidos)
// na janela. Retorna 0 quando não há amostra (caller usa sample_size para
// decidir se devolve NULL na API).
func (q *Queries) ChangeFailureRateInWindow(ctx context.Context, arg ChangeFailureRateInWindowParams) (ChangeFailureRateInWindowRow, error) {
	row := q.db.QueryRow(ctx, changeFailureRateInWindow, arg.ProjectID, arg.FinishedSince)
	var i ChangeFailureRateInWindowRow
	err := row.Scan(&i.Cfr, &i.SampleSize)
	return i, err
}

const countSuccessfulProductionDeploymentsInWindow = `-- name: CountSuccessfulProductionDeploymentsInWindow :one
SELECT COUNT(*) AS deploy_count
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
WHERE d.project_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
`

type CountSuccessfulProductionDeploymentsInWindowParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CountSuccessfulProductionDeploymentsInWindow(ctx context.Context, arg CountSuccessfulProductionDeploymentsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulProductionDeploymentsInWindow, arg.ProjectID, arg.FinishedAt)
	var deploy_count int64
	err := row.Scan(&deploy_count)
	return deploy_count, err
}

const leadTimeMedianSecondsInWindow = `-- name: LeadTimeMedianSecondsInWindow :one
SELECT
  COALESCE(
    PERCENTILE_CONT(0.5) WITHIN GROUP (
      ORDER BY EXTRACT(EPOCH FROM (d.finished_at - mr.first_commit_at))
    ),
    0
  ) AS median_seconds,
  COUNT(*) AS sample_size
FROM platform.deployment d
JOIN platform.environment e        ON e.id = d.environment_id
JOIN platform.deployment_mr_link l ON l.deployment_id = d.id
JOIN platform.merge_request mr     ON mr.id = l.merge_request_id
WHERE d.project_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
  AND mr.first_commit_at IS NOT NULL
  AND NOT mr.author_is_bot
`

type LeadTimeMedianSecondsInWindowParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type LeadTimeMedianSecondsInWindowRow struct {
	MedianSeconds interface{} `json:"median_seconds"`
	SampleSize    int64       `json:"sample_size"`
}

// Mediana de (deploy.finished_at - mr.first_commit_at) para os MRs
// atribuídos a deployments de produção bem-sucedidos na janela.
// COALESCE para 0 quando sample_size = 0 (PERCENTILE_CONT retorna NULL nesse caso).
// O caller DEVE checar sample_size > 0 antes de usar median_seconds.
func (q *Queries) LeadTimeMedianSecondsInWindow(ctx context.Context, arg LeadTimeMedianSecondsInWindowParams) (LeadTimeMedianSecondsInWindowRow, error) {
	row := q.db.QueryRow(ctx, leadTimeMedianSecondsInWindow, arg.ProjectID, arg.FinishedAt)
	var i LeadTimeMedianSecondsInWindowRow
	err := row.Scan(&i.MedianSeconds, &i.SampleSize)
	return i, err
}

const upsertDeployment = `-- name: UpsertDeployment :one
INSERT INTO platform.deployment (
  project_id, environment_id, external_id, sha, ref, status,
  triggered_by, started_at, finished_at, is_rollback, raw_payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (project_id, external_id) DO UPDATE
  SET status = EXCLUDED.status,
      finished_at = EXCLUDED.finished_at,
      raw_payload = EXCLUDED.raw_payload
RETURNING id, project_id, environment_id, external_id, sha, ref, status, triggered_by, started_at, finished_at, is_rollback, raw_payload
`

type UpsertDeploymentParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	EnvironmentID uuid.UUID          `json:"environment_id"`
	ExternalID    string             `json:"external_id"`
	Sha           string             `json:"sha"`
	Ref           *string            `json:"ref"`
	Status        string             `json:"status"`
	TriggeredBy   *string            `json:"triggered_by"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	IsRollback    bool               `json:"is_rollback"`
	RawPayload    []byte             `json:"raw_payload"`
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (PlatformDeployment, error) {
	row := q.db.QueryRow(ctx, upsertDeployment,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ExternalID,
		arg.Sha,
		arg.Ref,
		arg.Status,
		arg.TriggeredBy,
		arg.StartedAt,
		arg.FinishedAt,
		arg.IsRollback,
		arg.RawPayload,
	)
	var i PlatformDeployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.Sha,
		&i.Ref,
		&i.Status,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.IsRollback,
		&i.RawPayload,
	)
	return i, err
}
