// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_mr_links.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listProductionDeploymentsForProject = `-- name: ListProductionDeploymentsForProject :many
SELECT d.id, d.finished_at, d.environment_id, d.sha
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
WHERE d.project_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at IS NOT NULL
ORDER BY d.finished_at ASC
`

type ListProductionDeploymentsForProjectRow struct {
	ID            uuid.UUID          `json:"id"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	EnvironmentID uuid.UUID          `json:"environment_id"`
	Sha           string             `json:"sha"`
}

// Deployments de produção do projeto ordenados por finished_at ASC.
// Usado pela correlação MR ↔ deployment.
func (q *Queries) ListProductionDeploymentsForProject(ctx context.Context, projectID uuid.UUID) ([]ListProductionDeploymentsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listProductionDeploymentsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionDeploymentsForProjectRow{}
	for rows.Next() {
		var i ListProductionDeploymentsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.FinishedAt,
			&i.EnvironmentID,
			&i.Sha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeploymentMRLink = `-- name: UpsertDeploymentMRLink :exec
INSERT INTO platform.deployment_mr_link (deployment_id, merge_request_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertDeploymentMRLinkParams struct {
	DeploymentID   uuid.UUID `json:"deployment_id"`
	MergeRequestID uuid.UUID `json:"merge_request_id"`
}

func (q *Queries) UpsertDeploymentMRLink(ctx context.Context, arg UpsertDeploymentMRLinkParams) error {
	_, err := q.db.Exec(ctx, upsertDeploymentMRLink, arg.DeploymentID, arg.MergeRequestID)
	return err
}
