// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getProductionEnvironmentIDs = `-- name: GetProductionEnvironmentIDs :many
SELECT id FROM platform.environment
WHERE project_id = $1 AND is_production
`

func (q *Queries) GetProductionEnvironmentIDs(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getProductionEnvironmentIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, is_production, external_id, first_seen_at FROM platform.environment WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID uuid.UUID) ([]PlatformEnvironment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformEnvironment{}
	for rows.Next() {
		var i PlatformEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IsProduction,
			&i.ExternalID,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironment = `-- name: UpsertEnvironment :one
INSERT INTO platform.environment (project_id, name, is_production, external_id, first_seen_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, external_id) DO UPDATE
  SET name = EXCLUDED.name,
      is_production = EXCLUDED.is_production
RETURNING id, project_id, name, is_production, external_id, first_seen_at
`

type UpsertEnvironmentParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	Name         string    `json:"name"`
	IsProduction bool      `json:"is_production"`
	ExternalID   string    `json:"external_id"`
	FirstSeenAt  time.Time `json:"first_seen_at"`
}

func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (PlatformEnvironment, error) {
	row := q.db.QueryRow(ctx, upsertEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.IsProduction,
		arg.ExternalID,
		arg.FirstSeenAt,
	)
	var i PlatformEnvironment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsProduction,
		&i.ExternalID,
		&i.FirstSeenAt,
	)
	return i, err
}
