// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listIncidentsInWindowForProject = `-- name: ListIncidentsInWindowForProject :many
SELECT i.id,
       i.external_id,
       i.jira_project_key,
       i.summary,
       i.status,
       i.status_category,
       i.priority,
       i.issuetype,
       i.created_at,
       i.resolved_at
FROM platform.incident i
JOIN platform.project p
  ON p.tenant_id = i.tenant_id
  AND i.jira_project_key = ANY(p.jira_project_keys)
WHERE p.id = $1
  AND (i.created_at >= $2 OR i.resolved_at >= $2)
ORDER BY i.created_at DESC
`

type ListIncidentsInWindowForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Since     time.Time `json:"since"`
}

type ListIncidentsInWindowForProjectRow struct {
	ID             uuid.UUID          `json:"id"`
	ExternalID     string             `json:"external_id"`
	JiraProjectKey string             `json:"jira_project_key"`
	Summary        string             `json:"summary"`
	Status         string             `json:"status"`
	StatusCategory string             `json:"status_category"`
	Priority       *string            `json:"priority"`
	Issuetype      *string            `json:"issuetype"`
	CreatedAt      time.Time          `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

// Incidents do projeto cuja janela toca o intervalo: tanto os criados
// quanto os resolvidos a partir de `since` entram (cobre "abertos no
// período" e "fechados no período" — útil para auditoria de MTTR).
func (q *Queries) ListIncidentsInWindowForProject(ctx context.Context, arg ListIncidentsInWindowForProjectParams) ([]ListIncidentsInWindowForProjectRow, error) {
	rows, err := q.db.Query(ctx, listIncidentsInWindowForProject, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentsInWindowForProjectRow{}
	for rows.Next() {
		var i ListIncidentsInWindowForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.JiraProjectKey,
			&i.Summary,
			&i.Status,
			&i.StatusCategory,
			&i.Priority,
			&i.Issuetype,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMergedMRsInWindowForProject = `-- name: ListMergedMRsInWindowForProject :many
SELECT id,
       external_id,
       iid,
       title,
       author_username,
       target_branch,
       source_branch,
       merged_at,
       merge_commit_sha,
       first_commit_at,
       additions,
       deletions,
       web_url
FROM platform.merge_request
WHERE project_id = $1
  AND merged_at IS NOT NULL
  AND merged_at >= $2
  AND NOT author_is_bot
ORDER BY merged_at DESC
`

type ListMergedMRsInWindowForProjectParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	Since     pgtype.Timestamptz `json:"since"`
}

type ListMergedMRsInWindowForProjectRow struct {
	ID             uuid.UUID          `json:"id"`
	ExternalID     string             `json:"external_id"`
	Iid            int32              `json:"iid"`
	Title          string             `json:"title"`
	AuthorUsername *string            `json:"author_username"`
	TargetBranch   string             `json:"target_branch"`
	SourceBranch   *string            `json:"source_branch"`
	MergedAt       pgtype.Timestamptz `json:"merged_at"`
	MergeCommitSha *string            `json:"merge_commit_sha"`
	FirstCommitAt  pgtype.Timestamptz `json:"first_commit_at"`
	Additions      *int32             `json:"additions"`
	Deletions      *int32             `json:"deletions"`
	WebUrl         *string            `json:"web_url"`
}

// MRs do projeto mergeados a partir de `since`. Usado pelo export do
// drill-down (lista bruta sem depender de correlação com deploy).
func (q *Queries) ListMergedMRsInWindowForProject(ctx context.Context, arg ListMergedMRsInWindowForProjectParams) ([]ListMergedMRsInWindowForProjectRow, error) {
	rows, err := q.db.Query(ctx, listMergedMRsInWindowForProject, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergedMRsInWindowForProjectRow{}
	for rows.Next() {
		var i ListMergedMRsInWindowForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Iid,
			&i.Title,
			&i.AuthorUsername,
			&i.TargetBranch,
			&i.SourceBranch,
			&i.MergedAt,
			&i.MergeCommitSha,
			&i.FirstCommitAt,
			&i.Additions,
			&i.Deletions,
			&i.WebUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
