// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listIncidentsForProject = `-- name: ListIncidentsForProject :many
SELECT i.id, i.tenant_id, i.source_instance_id, i.external_id, i.jira_project_key, i.summary, i.status, i.status_category, i.priority, i.issuetype, i.labels, i.created_at, i.resolved_at, i.raw_payload
FROM platform.incident i
JOIN platform.project p
  ON p.tenant_id = i.tenant_id
  AND i.jira_project_key = ANY(p.jira_project_keys)
WHERE p.id = $1
ORDER BY i.created_at
`

// Incidents cujos jira_project_key estão no array do projeto. Usado pelo
// linking incident ↔ deployment e pelos cálculos por janela.
func (q *Queries) ListIncidentsForProject(ctx context.Context, projectID uuid.UUID) ([]PlatformIncident, error) {
	rows, err := q.db.Query(ctx, listIncidentsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformIncident{}
	for rows.Next() {
		var i PlatformIncident
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceInstanceID,
			&i.ExternalID,
			&i.JiraProjectKey,
			&i.Summary,
			&i.Status,
			&i.StatusCategory,
			&i.Priority,
			&i.Issuetype,
			&i.Labels,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.RawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mTTRMeanSecondsInWindow = `-- name: MTTRMeanSecondsInWindow :one
SELECT
  COALESCE(
    AVG(EXTRACT(EPOCH FROM (i.resolved_at - i.created_at))),
    0
  ) AS mean_seconds,
  COUNT(*) AS sample_size
FROM platform.incident i
JOIN platform.project p
  ON p.tenant_id = i.tenant_id
  AND i.jira_project_key = ANY(p.jira_project_keys)
WHERE p.id = $1
  AND i.resolved_at IS NOT NULL
  AND i.resolved_at >= $2
`

type MTTRMeanSecondsInWindowParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	ResolvedSince pgtype.Timestamptz `json:"resolved_since"`
}

type MTTRMeanSecondsInWindowRow struct {
	MeanSeconds interface{} `json:"mean_seconds"`
	SampleSize  int64       `json:"sample_size"`
}

// Média (segundos) de (resolved_at - created_at) para incidents do projeto
// resolvidos na janela. NULL quando não houver amostra; caller checa sample.
func (q *Queries) MTTRMeanSecondsInWindow(ctx context.Context, arg MTTRMeanSecondsInWindowParams) (MTTRMeanSecondsInWindowRow, error) {
	row := q.db.QueryRow(ctx, mTTRMeanSecondsInWindow, arg.ProjectID, arg.ResolvedSince)
	var i MTTRMeanSecondsInWindowRow
	err := row.Scan(&i.MeanSeconds, &i.SampleSize)
	return i, err
}

const upsertIncident = `-- name: UpsertIncident :one
INSERT INTO platform.incident (
  tenant_id, source_instance_id, external_id, jira_project_key,
  summary, status, status_category, priority, issuetype, labels,
  created_at, resolved_at, raw_payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (source_instance_id, external_id) DO UPDATE
  SET summary         = EXCLUDED.summary,
      status          = EXCLUDED.status,
      status_category = EXCLUDED.status_category,
      priority        = EXCLUDED.priority,
      issuetype       = EXCLUDED.issuetype,
      labels          = EXCLUDED.labels,
      resolved_at     = EXCLUDED.resolved_at,
      raw_payload     = EXCLUDED.raw_payload
RETURNING id, tenant_id, source_instance_id, external_id, jira_project_key, summary, status, status_category, priority, issuetype, labels, created_at, resolved_at, raw_payload
`

type UpsertIncidentParams struct {
	TenantID         uuid.UUID          `json:"tenant_id"`
	SourceInstanceID uuid.UUID          `json:"source_instance_id"`
	ExternalID       string             `json:"external_id"`
	JiraProjectKey   string             `json:"jira_project_key"`
	Summary          string             `json:"summary"`
	Status           string             `json:"status"`
	StatusCategory   string             `json:"status_category"`
	Priority         *string            `json:"priority"`
	Issuetype        *string            `json:"issuetype"`
	Labels           []string           `json:"labels"`
	CreatedAt        time.Time          `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	RawPayload       []byte             `json:"raw_payload"`
}

func (q *Queries) UpsertIncident(ctx context.Context, arg UpsertIncidentParams) (PlatformIncident, error) {
	row := q.db.QueryRow(ctx, upsertIncident,
		arg.TenantID,
		arg.SourceInstanceID,
		arg.ExternalID,
		arg.JiraProjectKey,
		arg.Summary,
		arg.Status,
		arg.StatusCategory,
		arg.Priority,
		arg.Issuetype,
		arg.Labels,
		arg.CreatedAt,
		arg.ResolvedAt,
		arg.RawPayload,
	)
	var i PlatformIncident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceInstanceID,
		&i.ExternalID,
		&i.JiraProjectKey,
		&i.Summary,
		&i.Status,
		&i.StatusCategory,
		&i.Priority,
		&i.Issuetype,
		&i.Labels,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.RawPayload,
	)
	return i, err
}
