// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_requests.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listMergedMRsBetween = `-- name: ListMergedMRsBetween :many
SELECT id, project_id, external_id, iid, title, author_username, author_is_bot, target_branch, source_branch, merged_at, merge_commit_sha, squash_commit_sha, first_commit_at, first_commit_sha, additions, deletions, labels, web_url, raw_payload, author_person_id FROM platform.merge_request
WHERE project_id = $1
  AND target_branch = ANY($2::text[])
  AND merged_at > $3
  AND merged_at <= $4
  AND NOT author_is_bot
`

type ListMergedMRsBetweenParams struct {
	ProjectID      uuid.UUID          `json:"project_id"`
	TargetBranches []string           `json:"target_branches"`
	MergedAfter    pgtype.Timestamptz `json:"merged_after"`
	MergedUntil    pgtype.Timestamptz `json:"merged_until"`
}

// MRs do projeto cujo merged_at cai no intervalo (gt, lte]. Usado para
// atribuir MRs ao deployment que "fechou" aquele intervalo de tempo.
func (q *Queries) ListMergedMRsBetween(ctx context.Context, arg ListMergedMRsBetweenParams) ([]PlatformMergeRequest, error) {
	rows, err := q.db.Query(ctx, listMergedMRsBetween,
		arg.ProjectID,
		arg.TargetBranches,
		arg.MergedAfter,
		arg.MergedUntil,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformMergeRequest{}
	for rows.Next() {
		var i PlatformMergeRequest
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalID,
			&i.Iid,
			&i.Title,
			&i.AuthorUsername,
			&i.AuthorIsBot,
			&i.TargetBranch,
			&i.SourceBranch,
			&i.MergedAt,
			&i.MergeCommitSha,
			&i.SquashCommitSha,
			&i.FirstCommitAt,
			&i.FirstCommitSha,
			&i.Additions,
			&i.Deletions,
			&i.Labels,
			&i.WebUrl,
			&i.RawPayload,
			&i.AuthorPersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMergeRequest = `-- name: UpsertMergeRequest :one
INSERT INTO platform.merge_request (
  project_id, external_id, iid, title, author_username, author_is_bot,
  target_branch, source_branch, merged_at, merge_commit_sha, squash_commit_sha,
  first_commit_at, first_commit_sha, additions, deletions, labels, web_url, raw_payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (project_id, external_id) DO UPDATE
  SET title             = EXCLUDED.title,
      author_username   = EXCLUDED.author_username,
      author_is_bot     = EXCLUDED.author_is_bot,
      target_branch     = EXCLUDED.target_branch,
      source_branch     = EXCLUDED.source_branch,
      merged_at         = EXCLUDED.merged_at,
      merge_commit_sha  = EXCLUDED.merge_commit_sha,
      squash_commit_sha = EXCLUDED.squash_commit_sha,
      first_commit_at   = EXCLUDED.first_commit_at,
      first_commit_sha  = EXCLUDED.first_commit_sha,
      additions         = EXCLUDED.additions,
      deletions         = EXCLUDED.deletions,
      labels            = EXCLUDED.labels,
      web_url           = EXCLUDED.web_url,
      raw_payload       = EXCLUDED.raw_payload
RETURNING id, project_id, external_id, iid, title, author_username, author_is_bot, target_branch, source_branch, merged_at, merge_commit_sha, squash_commit_sha, first_commit_at, first_commit_sha, additions, deletions, labels, web_url, raw_payload, author_person_id
`

type UpsertMergeRequestParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	ExternalID      string             `json:"external_id"`
	Iid             int32              `json:"iid"`
	Title           string             `json:"title"`
	AuthorUsername  *string            `json:"author_username"`
	AuthorIsBot     bool               `json:"author_is_bot"`
	TargetBranch    string             `json:"target_branch"`
	SourceBranch    *string            `json:"source_branch"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
	MergeCommitSha  *string            `json:"merge_commit_sha"`
	SquashCommitSha *string            `json:"squash_commit_sha"`
	FirstCommitAt   pgtype.Timestamptz `json:"first_commit_at"`
	FirstCommitSha  *string            `json:"first_commit_sha"`
	Additions       *int32             `json:"additions"`
	Deletions       *int32             `json:"deletions"`
	Labels          []string           `json:"labels"`
	WebUrl          *string            `json:"web_url"`
	RawPayload      []byte             `json:"raw_payload"`
}

func (q *Queries) UpsertMergeRequest(ctx context.Context, arg UpsertMergeRequestParams) (PlatformMergeRequest, error) {
	row := q.db.QueryRow(ctx, upsertMergeRequest,
		arg.ProjectID,
		arg.ExternalID,
		arg.Iid,
		arg.Title,
		arg.AuthorUsername,
		arg.AuthorIsBot,
		arg.TargetBranch,
		arg.SourceBranch,
		arg.MergedAt,
		arg.MergeCommitSha,
		arg.SquashCommitSha,
		arg.FirstCommitAt,
		arg.FirstCommitSha,
		arg.Additions,
		arg.Deletions,
		arg.Labels,
		arg.WebUrl,
		arg.RawPayload,
	)
	var i PlatformMergeRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Iid,
		&i.Title,
		&i.AuthorUsername,
		&i.AuthorIsBot,
		&i.TargetBranch,
		&i.SourceBranch,
		&i.MergedAt,
		&i.MergeCommitSha,
		&i.SquashCommitSha,
		&i.FirstCommitAt,
		&i.FirstCommitSha,
		&i.Additions,
		&i.Deletions,
		&i.Labels,
		&i.WebUrl,
		&i.RawPayload,
		&i.AuthorPersonID,
	)
	return i, err
}
