// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestMetricWindow = `-- name: GetLatestMetricWindow :one
SELECT tenant_id, scope_kind, scope_id, window_days, computed_at, deployment_frequency, lead_time_median_s, change_failure_rate, mttr_mean_s, classification, sample_size FROM metrics.metric_window
WHERE tenant_id = $1
  AND scope_kind = $2
  AND scope_id = $3
  AND window_days = $4
ORDER BY computed_at DESC
LIMIT 1
`

type GetLatestMetricWindowParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	ScopeKind  string    `json:"scope_kind"`
	ScopeID    uuid.UUID `json:"scope_id"`
	WindowDays int32     `json:"window_days"`
}

func (q *Queries) GetLatestMetricWindow(ctx context.Context, arg GetLatestMetricWindowParams) (MetricsMetricWindow, error) {
	row := q.db.QueryRow(ctx, getLatestMetricWindow,
		arg.TenantID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.WindowDays,
	)
	var i MetricsMetricWindow
	err := row.Scan(
		&i.TenantID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.WindowDays,
		&i.ComputedAt,
		&i.DeploymentFrequency,
		&i.LeadTimeMedianS,
		&i.ChangeFailureRate,
		&i.MttrMeanS,
		&i.Classification,
		&i.SampleSize,
	)
	return i, err
}

const upsertMetricWindow = `-- name: UpsertMetricWindow :one
INSERT INTO metrics.metric_window (
  tenant_id, scope_kind, scope_id, window_days, computed_at,
  deployment_frequency, lead_time_median_s, change_failure_rate, mttr_mean_s,
  classification, sample_size
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING tenant_id, scope_kind, scope_id, window_days, computed_at, deployment_frequency, lead_time_median_s, change_failure_rate, mttr_mean_s, classification, sample_size
`

type UpsertMetricWindowParams struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	ScopeKind           string         `json:"scope_kind"`
	ScopeID             uuid.UUID      `json:"scope_id"`
	WindowDays          int32          `json:"window_days"`
	ComputedAt          time.Time      `json:"computed_at"`
	DeploymentFrequency pgtype.Numeric `json:"deployment_frequency"`
	LeadTimeMedianS     *int64         `json:"lead_time_median_s"`
	ChangeFailureRate   pgtype.Numeric `json:"change_failure_rate"`
	MttrMeanS           *int64         `json:"mttr_mean_s"`
	Classification      *string        `json:"classification"`
	SampleSize          int32          `json:"sample_size"`
}

// Insere uma nova versão da janela (não substitui histórico).
func (q *Queries) UpsertMetricWindow(ctx context.Context, arg UpsertMetricWindowParams) (MetricsMetricWindow, error) {
	row := q.db.QueryRow(ctx, upsertMetricWindow,
		arg.TenantID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.WindowDays,
		arg.ComputedAt,
		arg.DeploymentFrequency,
		arg.LeadTimeMedianS,
		arg.ChangeFailureRate,
		arg.MttrMeanS,
		arg.Classification,
		arg.SampleSize,
	)
	var i MetricsMetricWindow
	err := row.Scan(
		&i.TenantID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.WindowDays,
		&i.ComputedAt,
		&i.DeploymentFrequency,
		&i.LeadTimeMedianS,
		&i.ChangeFailureRate,
		&i.MttrMeanS,
		&i.Classification,
		&i.SampleSize,
	)
	return i, err
}
