// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MetricsMetricDaily struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	ProjectID       uuid.UUID   `json:"project_id"`
	Day             pgtype.Date `json:"day"`
	DeployCount     int32       `json:"deploy_count"`
	DeployFailures  int32       `json:"deploy_failures"`
	LeadTimeP50     *int64      `json:"lead_time_p50"`
	LeadTimeP90     *int64      `json:"lead_time_p90"`
	IncidentsOpened int32       `json:"incidents_opened"`
	IncidentsClosed int32       `json:"incidents_closed"`
	MttrSecondsSum  *int64      `json:"mttr_seconds_sum"`
	MttrCount       int32       `json:"mttr_count"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type MetricsMetricMonthlySnapshot struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	ScopeKind           string         `json:"scope_kind"`
	ScopeID             uuid.UUID      `json:"scope_id"`
	Month               pgtype.Date    `json:"month"`
	DeploymentFrequency pgtype.Numeric `json:"deployment_frequency"`
	LeadTimeMedianS     *int64         `json:"lead_time_median_s"`
	ChangeFailureRate   pgtype.Numeric `json:"change_failure_rate"`
	MttrMeanS           *int64         `json:"mttr_mean_s"`
	Classification      *string        `json:"classification"`
}

type MetricsMetricWindow struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	ScopeKind           string         `json:"scope_kind"`
	ScopeID             uuid.UUID      `json:"scope_id"`
	WindowDays          int32          `json:"window_days"`
	ComputedAt          time.Time      `json:"computed_at"`
	DeploymentFrequency pgtype.Numeric `json:"deployment_frequency"`
	LeadTimeMedianS     *int64         `json:"lead_time_median_s"`
	ChangeFailureRate   pgtype.Numeric `json:"change_failure_rate"`
	MttrMeanS           *int64         `json:"mttr_mean_s"`
	Classification      *string        `json:"classification"`
	SampleSize          int32          `json:"sample_size"`
}

type PlatformClassificationThreshold struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Config   []byte    `json:"config"`
}

type PlatformDeployment struct {
	ID                uuid.UUID          `json:"id"`
	ProjectID         uuid.UUID          `json:"project_id"`
	EnvironmentID     uuid.UUID          `json:"environment_id"`
	ExternalID        string             `json:"external_id"`
	Sha               string             `json:"sha"`
	Ref               *string            `json:"ref"`
	Status            string             `json:"status"`
	TriggeredBy       *string            `json:"triggered_by"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	IsRollback        bool               `json:"is_rollback"`
	RawPayload        []byte             `json:"raw_payload"`
	TriggererPersonID pgtype.UUID        `json:"triggerer_person_id"`
}

type PlatformDeploymentIncidentLink struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	IncidentID   uuid.UUID `json:"incident_id"`
	LinkReason   string    `json:"link_reason"`
	LinkedAt     time.Time `json:"linked_at"`
}

type PlatformDeploymentMrLink struct {
	DeploymentID   uuid.UUID `json:"deployment_id"`
	MergeRequestID uuid.UUID `json:"merge_request_id"`
}

type PlatformEnvironment struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	Name         string    `json:"name"`
	IsProduction bool      `json:"is_production"`
	ExternalID   string    `json:"external_id"`
	FirstSeenAt  time.Time `json:"first_seen_at"`
}

type PlatformIncident struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	SourceInstanceID uuid.UUID          `json:"source_instance_id"`
	ExternalID       string             `json:"external_id"`
	JiraProjectKey   string             `json:"jira_project_key"`
	Summary          string             `json:"summary"`
	Status           string             `json:"status"`
	StatusCategory   string             `json:"status_category"`
	Priority         *string            `json:"priority"`
	Issuetype        *string            `json:"issuetype"`
	Labels           []string           `json:"labels"`
	CreatedAt        time.Time          `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	RawPayload       []byte             `json:"raw_payload"`
}

type PlatformMergeRequest struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	ExternalID      string             `json:"external_id"`
	Iid             int32              `json:"iid"`
	Title           string             `json:"title"`
	AuthorUsername  *string            `json:"author_username"`
	AuthorIsBot     bool               `json:"author_is_bot"`
	TargetBranch    string             `json:"target_branch"`
	SourceBranch    *string            `json:"source_branch"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
	MergeCommitSha  *string            `json:"merge_commit_sha"`
	SquashCommitSha *string            `json:"squash_commit_sha"`
	FirstCommitAt   pgtype.Timestamptz `json:"first_commit_at"`
	FirstCommitSha  *string            `json:"first_commit_sha"`
	Additions       *int32             `json:"additions"`
	Deletions       *int32             `json:"deletions"`
	Labels          []string           `json:"labels"`
	WebUrl          *string            `json:"web_url"`
	RawPayload      []byte             `json:"raw_payload"`
	AuthorPersonID  pgtype.UUID        `json:"author_person_id"`
}

type PlatformPerson struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	DisplayName  string    `json:"display_name"`
	PrimaryEmail *string   `json:"primary_email"`
	AvatarUrl    *string   `json:"avatar_url"`
	CreatedAt    time.Time `json:"created_at"`
}

type PlatformPersonIdentity struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	PersonID         pgtype.UUID        `json:"person_id"`
	SourceInstanceID pgtype.UUID        `json:"source_instance_id"`
	Kind             string             `json:"kind"`
	ExternalID       *string            `json:"external_id"`
	ExternalUsername string             `json:"external_username"`
	ExternalEmail    *string            `json:"external_email"`
	LinkedAt         pgtype.Timestamptz `json:"linked_at"`
	LinkedBy         *string            `json:"linked_by"`
	CreatedAt        time.Time          `json:"created_at"`
}

type PlatformProject struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	TeamID               pgtype.UUID        `json:"team_id"`
	SourceInstanceID     uuid.UUID          `json:"source_instance_id"`
	ExternalID           string             `json:"external_id"`
	PathWithNamespace    string             `json:"path_with_namespace"`
	DefaultBranch        string             `json:"default_branch"`
	ProductionEnvPattern string             `json:"production_env_pattern"`
	IncidentJql          string             `json:"incident_jql"`
	JiraProjectKeys      []string           `json:"jira_project_keys"`
	Active               bool               `json:"active"`
	CreatedAt            time.Time          `json:"created_at"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
}

type PlatformSourceInstance struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Kind        string    `json:"kind"`
	BaseUrl     string    `json:"base_url"`
	DisplayName string    `json:"display_name"`
	AuthRef     string    `json:"auth_ref"`
	CreatedAt   time.Time `json:"created_at"`
	// Token plaintext gravado via UI. Sensível — não logar nem expor em respostas REST.
	SecretValue *string `json:"secret_value"`
	// Email associado ao token (necessário para Jira Basic auth). NULL para GitLab.
	AuthEmail *string `json:"auth_email"`
}

type PlatformTeam struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Slug     string    `json:"slug"`
	Name     string    `json:"name"`
	// Hex CSS color, ex: #2563eb. Usado em chips/cards no dashboard.
	Color *string `json:"color"`
	// Emoji curto (1-2 caracteres) usado como mini-avatar.
	Emoji     *string   `json:"emoji"`
	CreatedAt time.Time `json:"created_at"`
}

type PlatformTenant struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type RawRawEvent struct {
	ID           int64              `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Source       string             `json:"source"`
	Kind         string             `json:"kind"`
	ExternalID   *string            `json:"external_id"`
	ReceivedAt   time.Time          `json:"received_at"`
	Payload      []byte             `json:"payload"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	ProcessError *string            `json:"process_error"`
}
