// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monthly_snapshot.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEliteMonthsForScope = `-- name: CountEliteMonthsForScope :one
SELECT COUNT(*)::bigint AS elite_months
FROM metrics.metric_monthly_snapshot
WHERE tenant_id = $1
  AND scope_kind = $2
  AND scope_id   = $3
  AND classification = 'elite'
`

type CountEliteMonthsForScopeParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ScopeKind string    `json:"scope_kind"`
	ScopeID   uuid.UUID `json:"scope_id"`
}

// Quantos meses na história desse scope foram classificados Elite.
// Drive da achievement "First Elite Month" (count >= 1).
func (q *Queries) CountEliteMonthsForScope(ctx context.Context, arg CountEliteMonthsForScopeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEliteMonthsForScope, arg.TenantID, arg.ScopeKind, arg.ScopeID)
	var elite_months int64
	err := row.Scan(&elite_months)
	return elite_months, err
}

const getLastIncidentsMTTRForProject = `-- name: GetLastIncidentsMTTRForProject :many
SELECT
  i.id,
  i.resolved_at,
  EXTRACT(EPOCH FROM (i.resolved_at - i.created_at))::bigint AS mttr_seconds
FROM platform.incident i
JOIN platform.project p
  ON p.tenant_id = i.tenant_id
  AND i.jira_project_key = ANY(p.jira_project_keys)
WHERE p.id = $1
  AND i.resolved_at IS NOT NULL
ORDER BY i.resolved_at DESC
LIMIT $2
`

type GetLastIncidentsMTTRForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	LimitN    int32     `json:"limit_n"`
}

type GetLastIncidentsMTTRForProjectRow struct {
	ID          uuid.UUID          `json:"id"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	MttrSeconds int64              `json:"mttr_seconds"`
}

// Últimos 5 incidents resolvidos do projeto (via jira_project_keys),
// com o MTTR em segundos. Drive da achievement "Recovery Master".
func (q *Queries) GetLastIncidentsMTTRForProject(ctx context.Context, arg GetLastIncidentsMTTRForProjectParams) ([]GetLastIncidentsMTTRForProjectRow, error) {
	rows, err := q.db.Query(ctx, getLastIncidentsMTTRForProject, arg.ProjectID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLastIncidentsMTTRForProjectRow{}
	for rows.Next() {
		var i GetLastIncidentsMTTRForProjectRow
		if err := rows.Scan(&i.ID, &i.ResolvedAt, &i.MttrSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonthlySnapshot = `-- name: UpsertMonthlySnapshot :one
INSERT INTO metrics.metric_monthly_snapshot (
  tenant_id, scope_kind, scope_id, month,
  deployment_frequency, lead_time_median_s, change_failure_rate, mttr_mean_s,
  classification
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (tenant_id, scope_kind, scope_id, month) DO UPDATE
  SET deployment_frequency = EXCLUDED.deployment_frequency,
      lead_time_median_s   = EXCLUDED.lead_time_median_s,
      change_failure_rate  = EXCLUDED.change_failure_rate,
      mttr_mean_s          = EXCLUDED.mttr_mean_s,
      classification       = EXCLUDED.classification
RETURNING tenant_id, scope_kind, scope_id, month, deployment_frequency, lead_time_median_s, change_failure_rate, mttr_mean_s, classification
`

type UpsertMonthlySnapshotParams struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	ScopeKind           string         `json:"scope_kind"`
	ScopeID             uuid.UUID      `json:"scope_id"`
	Month               pgtype.Date    `json:"month"`
	DeploymentFrequency pgtype.Numeric `json:"deployment_frequency"`
	LeadTimeMedianS     *int64         `json:"lead_time_median_s"`
	ChangeFailureRate   pgtype.Numeric `json:"change_failure_rate"`
	MttrMeanS           *int64         `json:"mttr_mean_s"`
	Classification      *string        `json:"classification"`
}

func (q *Queries) UpsertMonthlySnapshot(ctx context.Context, arg UpsertMonthlySnapshotParams) (MetricsMetricMonthlySnapshot, error) {
	row := q.db.QueryRow(ctx, upsertMonthlySnapshot,
		arg.TenantID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Month,
		arg.DeploymentFrequency,
		arg.LeadTimeMedianS,
		arg.ChangeFailureRate,
		arg.MttrMeanS,
		arg.Classification,
	)
	var i MetricsMetricMonthlySnapshot
	err := row.Scan(
		&i.TenantID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Month,
		&i.DeploymentFrequency,
		&i.LeadTimeMedianS,
		&i.ChangeFailureRate,
		&i.MttrMeanS,
		&i.Classification,
	)
	return i, err
}
