// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO platform.person (tenant_id, display_name, primary_email, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, display_name, primary_email, avatar_url, created_at
`

type CreatePersonParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	DisplayName  string    `json:"display_name"`
	PrimaryEmail *string   `json:"primary_email"`
	AvatarUrl    *string   `json:"avatar_url"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (PlatformPerson, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.TenantID,
		arg.DisplayName,
		arg.PrimaryEmail,
		arg.AvatarUrl,
	)
	var i PlatformPerson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.PrimaryEmail,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const findIdentitiesByEmail = `-- name: FindIdentitiesByEmail :many
SELECT id, tenant_id, person_id, source_instance_id, kind, external_id, external_username, external_email, linked_at, linked_by, created_at FROM platform.person_identity
WHERE tenant_id = $1
  AND external_email IS NOT NULL
  AND lower(external_email) = lower($2::text)
`

type FindIdentitiesByEmailParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Email    string    `json:"email"`
}

// Auto-match heurístico: identidades com mesmo email (ignorando case).
func (q *Queries) FindIdentitiesByEmail(ctx context.Context, arg FindIdentitiesByEmailParams) ([]PlatformPersonIdentity, error) {
	rows, err := q.db.Query(ctx, findIdentitiesByEmail, arg.TenantID, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPersonIdentity{}
	for rows.Next() {
		var i PlatformPersonIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.SourceInstanceID,
			&i.Kind,
			&i.ExternalID,
			&i.ExternalUsername,
			&i.ExternalEmail,
			&i.LinkedAt,
			&i.LinkedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findIdentitiesByUsername = `-- name: FindIdentitiesByUsername :many
SELECT id, tenant_id, person_id, source_instance_id, kind, external_id, external_username, external_email, linked_at, linked_by, created_at FROM platform.person_identity
WHERE tenant_id = $1
  AND lower(external_username) = lower($2::text)
`

type FindIdentitiesByUsernameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Username string    `json:"username"`
}

// Auto-match heurístico: identidades com mesmo username (ignorando case),
// entre diferentes kinds. Usado para sugerir merges de "alice" do GitLab com
// "alice" do Jira quando emails não estão disponíveis.
func (q *Queries) FindIdentitiesByUsername(ctx context.Context, arg FindIdentitiesByUsernameParams) ([]PlatformPersonIdentity, error) {
	rows, err := q.db.Query(ctx, findIdentitiesByUsername, arg.TenantID, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPersonIdentity{}
	for rows.Next() {
		var i PlatformPersonIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.SourceInstanceID,
			&i.Kind,
			&i.ExternalID,
			&i.ExternalUsername,
			&i.ExternalEmail,
			&i.LinkedAt,
			&i.LinkedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPersonByEmail = `-- name: FindPersonByEmail :one
SELECT id, tenant_id, display_name, primary_email, avatar_url, created_at FROM platform.person
WHERE tenant_id = $1
  AND lower(primary_email) = lower($2::text)
LIMIT 1
`

type FindPersonByEmailParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Email    string    `json:"email"`
}

// Auto-match: dado um email, devolve a person que casa.
func (q *Queries) FindPersonByEmail(ctx context.Context, arg FindPersonByEmailParams) (PlatformPerson, error) {
	row := q.db.QueryRow(ctx, findPersonByEmail, arg.TenantID, arg.Email)
	var i PlatformPerson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.PrimaryEmail,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, tenant_id, display_name, primary_email, avatar_url, created_at FROM platform.person WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (PlatformPerson, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i PlatformPerson
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.PrimaryEmail,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const linkIdentityToPerson = `-- name: LinkIdentityToPerson :one
UPDATE platform.person_identity
SET person_id = $1,
    linked_at = now(),
    linked_by = $2
WHERE id = $3
RETURNING id, tenant_id, person_id, source_instance_id, kind, external_id, external_username, external_email, linked_at, linked_by, created_at
`

type LinkIdentityToPersonParams struct {
	PersonID   pgtype.UUID `json:"person_id"`
	LinkedBy   *string     `json:"linked_by"`
	IdentityID uuid.UUID   `json:"identity_id"`
}

func (q *Queries) LinkIdentityToPerson(ctx context.Context, arg LinkIdentityToPersonParams) (PlatformPersonIdentity, error) {
	row := q.db.QueryRow(ctx, linkIdentityToPerson, arg.PersonID, arg.LinkedBy, arg.IdentityID)
	var i PlatformPersonIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.SourceInstanceID,
		&i.Kind,
		&i.ExternalID,
		&i.ExternalUsername,
		&i.ExternalEmail,
		&i.LinkedAt,
		&i.LinkedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listGitlabUsernamesFromEvents = `-- name: ListGitlabUsernamesFromEvents :many
SELECT DISTINCT lower(username) AS username
FROM (
  SELECT mr.author_username AS username
  FROM platform.merge_request mr
  JOIN platform.project p ON p.id = mr.project_id
  WHERE p.tenant_id = $1
    AND mr.author_username IS NOT NULL
    AND mr.author_username <> ''
    AND NOT mr.author_is_bot
  UNION
  SELECT d.triggered_by AS username
  FROM platform.deployment d
  JOIN platform.project p ON p.id = d.project_id
  WHERE p.tenant_id = $1
    AND d.triggered_by IS NOT NULL
    AND d.triggered_by <> ''
) AS sources
WHERE username IS NOT NULL AND username <> ''
ORDER BY username
`

// Backfill: usernames únicos que já apareceram em merge_request.author_username
// ou deployment.triggered_by, restrito ao tenant via JOIN com project.
func (q *Queries) ListGitlabUsernamesFromEvents(ctx context.Context, tenantID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listGitlabUsernamesFromEvents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByPerson = `-- name: ListIdentitiesByPerson :many
SELECT id, tenant_id, person_id, source_instance_id, kind, external_id, external_username, external_email, linked_at, linked_by, created_at FROM platform.person_identity
WHERE person_id = $1
ORDER BY kind, external_username
`

func (q *Queries) ListIdentitiesByPerson(ctx context.Context, personID pgtype.UUID) ([]PlatformPersonIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPersonIdentity{}
	for rows.Next() {
		var i PlatformPersonIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.SourceInstanceID,
			&i.Kind,
			&i.ExternalID,
			&i.ExternalUsername,
			&i.ExternalEmail,
			&i.LinkedAt,
			&i.LinkedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeople = `-- name: ListPeople :many
SELECT id, tenant_id, display_name, primary_email, avatar_url, created_at FROM platform.person
WHERE tenant_id = $1
ORDER BY display_name
`

func (q *Queries) ListPeople(ctx context.Context, tenantID uuid.UUID) ([]PlatformPerson, error) {
	rows, err := q.db.Query(ctx, listPeople, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPerson{}
	for rows.Next() {
		var i PlatformPerson
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DisplayName,
			&i.PrimaryEmail,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlinkedIdentities = `-- name: ListUnlinkedIdentities :many
SELECT id, tenant_id, person_id, source_instance_id, kind, external_id, external_username, external_email, linked_at, linked_by, created_at FROM platform.person_identity
WHERE tenant_id = $1
  AND person_id IS NULL
ORDER BY kind, external_username
`

func (q *Queries) ListUnlinkedIdentities(ctx context.Context, tenantID uuid.UUID) ([]PlatformPersonIdentity, error) {
	rows, err := q.db.Query(ctx, listUnlinkedIdentities, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPersonIdentity{}
	for rows.Next() {
		var i PlatformPersonIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.SourceInstanceID,
			&i.Kind,
			&i.ExternalID,
			&i.ExternalUsername,
			&i.ExternalEmail,
			&i.LinkedAt,
			&i.LinkedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkIdentity = `-- name: UnlinkIdentity :exec
UPDATE platform.person_identity
SET person_id = NULL,
    linked_at = NULL,
    linked_by = NULL
WHERE id = $1
`

func (q *Queries) UnlinkIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkIdentity, id)
	return err
}

const upsertPersonIdentity = `-- name: UpsertPersonIdentity :one
INSERT INTO platform.person_identity (
  tenant_id, source_instance_id, kind,
  external_id, external_username, external_email
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, kind, external_username) DO UPDATE
  SET external_email = COALESCE(EXCLUDED.external_email, platform.person_identity.external_email),
      external_id    = COALESCE(EXCLUDED.external_id, platform.person_identity.external_id),
      source_instance_id = COALESCE(EXCLUDED.source_instance_id, platform.person_identity.source_instance_id)
RETURNING id, tenant_id, person_id, source_instance_id, kind, external_id, external_username, external_email, linked_at, linked_by, created_at
`

type UpsertPersonIdentityParams struct {
	TenantID         uuid.UUID   `json:"tenant_id"`
	SourceInstanceID pgtype.UUID `json:"source_instance_id"`
	Kind             string      `json:"kind"`
	ExternalID       *string     `json:"external_id"`
	ExternalUsername string      `json:"external_username"`
	ExternalEmail    *string     `json:"external_email"`
}

// Idempotente em (tenant_id, kind, external_username). Atualiza external_email
// e external_id no conflito; preserva person_id já vinculado.
func (q *Queries) UpsertPersonIdentity(ctx context.Context, arg UpsertPersonIdentityParams) (PlatformPersonIdentity, error) {
	row := q.db.QueryRow(ctx, upsertPersonIdentity,
		arg.TenantID,
		arg.SourceInstanceID,
		arg.Kind,
		arg.ExternalID,
		arg.ExternalUsername,
		arg.ExternalEmail,
	)
	var i PlatformPersonIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.SourceInstanceID,
		&i.Kind,
		&i.ExternalID,
		&i.ExternalUsername,
		&i.ExternalEmail,
		&i.LinkedAt,
		&i.LinkedBy,
		&i.CreatedAt,
	)
	return i, err
}
