// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO platform.project (
  tenant_id, team_id, source_instance_id, external_id, path_with_namespace,
  default_branch, production_env_pattern, incident_jql, jira_project_keys
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at
`

type CreateProjectParams struct {
	TenantID             uuid.UUID   `json:"tenant_id"`
	TeamID               pgtype.UUID `json:"team_id"`
	SourceInstanceID     uuid.UUID   `json:"source_instance_id"`
	ExternalID           string      `json:"external_id"`
	PathWithNamespace    string      `json:"path_with_namespace"`
	DefaultBranch        string      `json:"default_branch"`
	ProductionEnvPattern string      `json:"production_env_pattern"`
	IncidentJql          string      `json:"incident_jql"`
	JiraProjectKeys      []string    `json:"jira_project_keys"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (PlatformProject, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.TeamID,
		arg.SourceInstanceID,
		arg.ExternalID,
		arg.PathWithNamespace,
		arg.DefaultBranch,
		arg.ProductionEnvPattern,
		arg.IncidentJql,
		arg.JiraProjectKeys,
	)
	var i PlatformProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.SourceInstanceID,
		&i.ExternalID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.ProductionEnvPattern,
		&i.IncidentJql,
		&i.JiraProjectKeys,
		&i.Active,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const getGitLabProjectByExternalID = `-- name: GetGitLabProjectByExternalID :one
SELECT p.id, p.tenant_id, p.team_id, p.source_instance_id, p.external_id, p.path_with_namespace, p.default_branch, p.production_env_pattern, p.incident_jql, p.jira_project_keys, p.active, p.created_at, p.last_synced_at
FROM platform.project p
JOIN platform.source_instance si ON si.id = p.source_instance_id
WHERE si.kind = 'gitlab'
  AND p.external_id = $1
ORDER BY p.created_at
LIMIT 1
`

// Encontra o projeto pelo external_id assumindo source kind='gitlab'.
// Em multi-tenant com múltiplos GitLab e overlap de IDs, retorna o mais antigo.
func (q *Queries) GetGitLabProjectByExternalID(ctx context.Context, externalID string) (PlatformProject, error) {
	row := q.db.QueryRow(ctx, getGitLabProjectByExternalID, externalID)
	var i PlatformProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.SourceInstanceID,
		&i.ExternalID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.ProductionEnvPattern,
		&i.IncidentJql,
		&i.JiraProjectKeys,
		&i.Active,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at FROM platform.project WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (PlatformProject, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i PlatformProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.SourceInstanceID,
		&i.ExternalID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.ProductionEnvPattern,
		&i.IncidentJql,
		&i.JiraProjectKeys,
		&i.Active,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const getProjectByExternalID = `-- name: GetProjectByExternalID :one
SELECT id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at FROM platform.project
WHERE source_instance_id = $1 AND external_id = $2
`

type GetProjectByExternalIDParams struct {
	SourceInstanceID uuid.UUID `json:"source_instance_id"`
	ExternalID       string    `json:"external_id"`
}

func (q *Queries) GetProjectByExternalID(ctx context.Context, arg GetProjectByExternalIDParams) (PlatformProject, error) {
	row := q.db.QueryRow(ctx, getProjectByExternalID, arg.SourceInstanceID, arg.ExternalID)
	var i PlatformProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.SourceInstanceID,
		&i.ExternalID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.ProductionEnvPattern,
		&i.IncidentJql,
		&i.JiraProjectKeys,
		&i.Active,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const listActiveProjects = `-- name: ListActiveProjects :many
SELECT id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at FROM platform.project WHERE active ORDER BY last_synced_at NULLS FIRST
`

func (q *Queries) ListActiveProjects(ctx context.Context) ([]PlatformProject, error) {
	rows, err := q.db.Query(ctx, listActiveProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformProject{}
	for rows.Next() {
		var i PlatformProject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.SourceInstanceID,
			&i.ExternalID,
			&i.PathWithNamespace,
			&i.DefaultBranch,
			&i.ProductionEnvPattern,
			&i.IncidentJql,
			&i.JiraProjectKeys,
			&i.Active,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProjectsByJiraProjectKey = `-- name: ListActiveProjectsByJiraProjectKey :many
SELECT id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at FROM platform.project
WHERE active
  AND $1::text = ANY(jira_project_keys)
`

// Projects cujos jira_project_keys contêm a chave passada (case-sensitive).
// Usado por webhook Jira para identificar quais nossos projetos refrescar.
func (q *Queries) ListActiveProjectsByJiraProjectKey(ctx context.Context, jiraProjectKey string) ([]PlatformProject, error) {
	rows, err := q.db.Query(ctx, listActiveProjectsByJiraProjectKey, jiraProjectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformProject{}
	for rows.Next() {
		var i PlatformProject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.SourceInstanceID,
			&i.ExternalID,
			&i.PathWithNamespace,
			&i.DefaultBranch,
			&i.ProductionEnvPattern,
			&i.IncidentJql,
			&i.JiraProjectKeys,
			&i.Active,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at FROM platform.project ORDER BY path_with_namespace
`

func (q *Queries) ListProjects(ctx context.Context) ([]PlatformProject, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformProject{}
	for rows.Next() {
		var i PlatformProject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.SourceInstanceID,
			&i.ExternalID,
			&i.PathWithNamespace,
			&i.DefaultBranch,
			&i.ProductionEnvPattern,
			&i.IncidentJql,
			&i.JiraProjectKeys,
			&i.Active,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectLastSynced = `-- name: UpdateProjectLastSynced :exec
UPDATE platform.project SET last_synced_at = $2 WHERE id = $1
`

type UpdateProjectLastSyncedParams struct {
	ID           uuid.UUID          `json:"id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateProjectLastSynced(ctx context.Context, arg UpdateProjectLastSyncedParams) error {
	_, err := q.db.Exec(ctx, updateProjectLastSynced, arg.ID, arg.LastSyncedAt)
	return err
}
