// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// (deploys com >= 1 incident vinculado) / (deploys de produção bem-sucedidos)
	// na janela. Retorna 0 quando não há amostra (caller usa sample_size para
	// decidir se devolve NULL na API).
	ChangeFailureRateInWindow(ctx context.Context, arg ChangeFailureRateInWindowParams) (ChangeFailureRateInWindowRow, error)
	CountSuccessfulProductionDeploymentsInWindow(ctx context.Context, arg CountSuccessfulProductionDeploymentsInWindowParams) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (PlatformProject, error)
	CreateSourceInstance(ctx context.Context, arg CreateSourceInstanceParams) (PlatformSourceInstance, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (PlatformTenant, error)
	// Série temporal de deployments de produção bem-sucedidos por dia (UTC).
	// Drive da curva de Deployment Frequency.
	DeploymentsPerDayInWindow(ctx context.Context, arg DeploymentsPerDayInWindowParams) ([]DeploymentsPerDayInWindowRow, error)
	// Acha o deployment de produção bem-sucedido mais recente do projeto cujo
	// finished_at está em (incident.created_at - lookback, incident.created_at].
	// Usado pelo time-window linking de CFR (default lookback = 24h).
	FindDeploymentForIncident(ctx context.Context, arg FindDeploymentForIncidentParams) (uuid.UUID, error)
	GetClassificationThreshold(ctx context.Context, tenantID uuid.UUID) (PlatformClassificationThreshold, error)
	GetFirstSourceInstanceForTenantKind(ctx context.Context, arg GetFirstSourceInstanceForTenantKindParams) (PlatformSourceInstance, error)
	// Encontra o projeto pelo external_id assumindo source kind='gitlab'.
	// Em multi-tenant com múltiplos GitLab e overlap de IDs, retorna o mais antigo.
	GetGitLabProjectByExternalID(ctx context.Context, externalID string) (PlatformProject, error)
	GetLatestMetricWindow(ctx context.Context, arg GetLatestMetricWindowParams) (MetricsMetricWindow, error)
	GetProductionEnvironmentIDs(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error)
	GetProject(ctx context.Context, id uuid.UUID) (PlatformProject, error)
	GetProjectByExternalID(ctx context.Context, arg GetProjectByExternalIDParams) (PlatformProject, error)
	GetSourceInstance(ctx context.Context, id uuid.UUID) (PlatformSourceInstance, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (PlatformTenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (PlatformTenant, error)
	InsertRawEvent(ctx context.Context, arg InsertRawEventParams) (RawRawEvent, error)
	// Mediana de (deploy.finished_at - mr.first_commit_at) para os MRs
	// atribuídos a deployments de produção bem-sucedidos na janela.
	// COALESCE para 0 quando sample_size = 0 (PERCENTILE_CONT retorna NULL nesse caso).
	// O caller DEVE checar sample_size > 0 antes de usar median_seconds.
	LeadTimeMedianSecondsInWindow(ctx context.Context, arg LeadTimeMedianSecondsInWindowParams) (LeadTimeMedianSecondsInWindowRow, error)
	ListActiveProjects(ctx context.Context) ([]PlatformProject, error)
	// Projects cujos jira_project_keys contêm a chave passada (case-sensitive).
	// Usado por webhook Jira para identificar quais nossos projetos refrescar.
	ListActiveProjectsByJiraProjectKey(ctx context.Context, jiraProjectKey string) ([]PlatformProject, error)
	ListEnvironmentsByProject(ctx context.Context, projectID uuid.UUID) ([]PlatformEnvironment, error)
	// Incidents cujos jira_project_key estão no array do projeto. Usado pelo
	// linking incident ↔ deployment e pelos cálculos por janela.
	ListIncidentsForProject(ctx context.Context, projectID uuid.UUID) ([]PlatformIncident, error)
	// MRs do projeto cujo merged_at cai no intervalo (gt, lte]. Usado para
	// atribuir MRs ao deployment que "fechou" aquele intervalo de tempo.
	ListMergedMRsBetween(ctx context.Context, arg ListMergedMRsBetweenParams) ([]PlatformMergeRequest, error)
	// Deployments de produção do projeto ordenados por finished_at ASC.
	// Usado pela correlação MR ↔ deployment.
	ListProductionDeploymentsForProject(ctx context.Context, projectID uuid.UUID) ([]ListProductionDeploymentsForProjectRow, error)
	// Lista bruta dos deploys de produção na janela. Drive do drill-down
	// "clique no tile/ponto → ver os deploys que compõem".
	ListProductionDeploymentsInWindow(ctx context.Context, arg ListProductionDeploymentsInWindowParams) ([]ListProductionDeploymentsInWindowRow, error)
	ListProjects(ctx context.Context) ([]PlatformProject, error)
	ListSourceInstancesByTenant(ctx context.Context, tenantID uuid.UUID) ([]PlatformSourceInstance, error)
	ListTenants(ctx context.Context) ([]PlatformTenant, error)
	// Fila do processamento incremental — usa o índice parcial
	// raw_event_pending_idx (processed_at IS NULL).
	ListUnprocessedRawEvents(ctx context.Context, batchSize int32) ([]RawRawEvent, error)
	// Média (segundos) de (resolved_at - created_at) para incidents do projeto
	// resolvidos na janela. NULL quando não houver amostra; caller checa sample.
	MTTRMeanSecondsInWindow(ctx context.Context, arg MTTRMeanSecondsInWindowParams) (MTTRMeanSecondsInWindowRow, error)
	MarkRawEventProcessed(ctx context.Context, arg MarkRawEventProcessedParams) error
	UpdateProjectLastSynced(ctx context.Context, arg UpdateProjectLastSyncedParams) error
	UpsertClassificationThreshold(ctx context.Context, arg UpsertClassificationThresholdParams) (PlatformClassificationThreshold, error)
	UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (PlatformDeployment, error)
	UpsertDeploymentIncidentLink(ctx context.Context, arg UpsertDeploymentIncidentLinkParams) error
	UpsertDeploymentMRLink(ctx context.Context, arg UpsertDeploymentMRLinkParams) error
	UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (PlatformEnvironment, error)
	UpsertIncident(ctx context.Context, arg UpsertIncidentParams) (PlatformIncident, error)
	UpsertMergeRequest(ctx context.Context, arg UpsertMergeRequestParams) (PlatformMergeRequest, error)
	// Insere uma nova versão da janela (não substitui histórico).
	UpsertMetricWindow(ctx context.Context, arg UpsertMetricWindowParams) (MetricsMetricWindow, error)
}

var _ Querier = (*Queries)(nil)
