// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw_events.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const insertRawEvent = `-- name: InsertRawEvent :one
INSERT INTO raw.raw_event (tenant_id, source, kind, external_id, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, source, kind, external_id, received_at, payload, processed_at, process_error
`

type InsertRawEventParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Source     string    `json:"source"`
	Kind       string    `json:"kind"`
	ExternalID *string   `json:"external_id"`
	Payload    []byte    `json:"payload"`
}

func (q *Queries) InsertRawEvent(ctx context.Context, arg InsertRawEventParams) (RawRawEvent, error) {
	row := q.db.QueryRow(ctx, insertRawEvent,
		arg.TenantID,
		arg.Source,
		arg.Kind,
		arg.ExternalID,
		arg.Payload,
	)
	var i RawRawEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Kind,
		&i.ExternalID,
		&i.ReceivedAt,
		&i.Payload,
		&i.ProcessedAt,
		&i.ProcessError,
	)
	return i, err
}

const listUnprocessedRawEvents = `-- name: ListUnprocessedRawEvents :many
SELECT id, tenant_id, source, kind, external_id, received_at, payload, processed_at, process_error FROM raw.raw_event
WHERE processed_at IS NULL
ORDER BY id
LIMIT $1
`

// Fila do processamento incremental — usa o índice parcial
// raw_event_pending_idx (processed_at IS NULL).
func (q *Queries) ListUnprocessedRawEvents(ctx context.Context, batchSize int32) ([]RawRawEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedRawEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawRawEvent{}
	for rows.Next() {
		var i RawRawEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.Kind,
			&i.ExternalID,
			&i.ReceivedAt,
			&i.Payload,
			&i.ProcessedAt,
			&i.ProcessError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRawEventProcessed = `-- name: MarkRawEventProcessed :exec
UPDATE raw.raw_event
SET processed_at = now(),
    process_error = $1
WHERE id = $2
`

type MarkRawEventProcessedParams struct {
	ProcessError *string `json:"process_error"`
	ID           int64   `json:"id"`
}

func (q *Queries) MarkRawEventProcessed(ctx context.Context, arg MarkRawEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markRawEventProcessed, arg.ProcessError, arg.ID)
	return err
}
