// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source_instances.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createSourceInstance = `-- name: CreateSourceInstance :one
INSERT INTO platform.source_instance (tenant_id, kind, base_url, display_name, auth_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, kind, base_url, display_name, auth_ref, created_at
`

type CreateSourceInstanceParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	Kind        string    `json:"kind"`
	BaseUrl     string    `json:"base_url"`
	DisplayName string    `json:"display_name"`
	AuthRef     string    `json:"auth_ref"`
}

func (q *Queries) CreateSourceInstance(ctx context.Context, arg CreateSourceInstanceParams) (PlatformSourceInstance, error) {
	row := q.db.QueryRow(ctx, createSourceInstance,
		arg.TenantID,
		arg.Kind,
		arg.BaseUrl,
		arg.DisplayName,
		arg.AuthRef,
	)
	var i PlatformSourceInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.BaseUrl,
		&i.DisplayName,
		&i.AuthRef,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceInstance = `-- name: GetSourceInstance :one
SELECT id, tenant_id, kind, base_url, display_name, auth_ref, created_at FROM platform.source_instance WHERE id = $1
`

func (q *Queries) GetSourceInstance(ctx context.Context, id uuid.UUID) (PlatformSourceInstance, error) {
	row := q.db.QueryRow(ctx, getSourceInstance, id)
	var i PlatformSourceInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.BaseUrl,
		&i.DisplayName,
		&i.AuthRef,
		&i.CreatedAt,
	)
	return i, err
}

const listSourceInstancesByTenant = `-- name: ListSourceInstancesByTenant :many
SELECT id, tenant_id, kind, base_url, display_name, auth_ref, created_at FROM platform.source_instance
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListSourceInstancesByTenant(ctx context.Context, tenantID uuid.UUID) ([]PlatformSourceInstance, error) {
	rows, err := q.db.Query(ctx, listSourceInstancesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSourceInstance{}
	for rows.Next() {
		var i PlatformSourceInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.BaseUrl,
			&i.DisplayName,
			&i.AuthRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
