// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streaks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const daysSinceLastIncidentForProject = `-- name: DaysSinceLastIncidentForProject :one
SELECT
  FLOOR(EXTRACT(EPOCH FROM (now() - MAX(i.created_at))) / 86400)::int AS days_since
FROM platform.incident i
JOIN platform.project p
  ON p.tenant_id = i.tenant_id
  AND i.jira_project_key = ANY(p.jira_project_keys)
WHERE p.id = $1
`

// Dias completos desde o último incident production-impactante do projeto
// (via mapping jira_project_keys). NULL se o projeto nunca teve incident
// ou se não tem jira_project_keys configurado.
func (q *Queries) DaysSinceLastIncidentForProject(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, daysSinceLastIncidentForProject, projectID)
	var days_since int32
	err := row.Scan(&days_since)
	return days_since, err
}
