// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_metrics.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeFailureRateForTeamInWindow = `-- name: ChangeFailureRateForTeamInWindow :one
SELECT
  COALESCE(
    CAST(SUM(CASE WHEN linked_count > 0 THEN 1 ELSE 0 END) AS numeric)
      / NULLIF(COUNT(*), 0),
    0
  ) AS cfr,
  COUNT(*) AS sample_size
FROM (
  SELECT d.id, COUNT(dil.incident_id) AS linked_count
  FROM platform.deployment d
  JOIN platform.environment e ON e.id = d.environment_id
  JOIN platform.project p     ON p.id = d.project_id
  LEFT JOIN platform.deployment_incident_link dil ON dil.deployment_id = d.id
  WHERE p.team_id = $1
    AND e.is_production
    AND d.status = 'success'
    AND d.finished_at >= $2
  GROUP BY d.id
) AS by_deploy
`

type ChangeFailureRateForTeamInWindowParams struct {
	TeamID        pgtype.UUID        `json:"team_id"`
	FinishedSince pgtype.Timestamptz `json:"finished_since"`
}

type ChangeFailureRateForTeamInWindowRow struct {
	Cfr        interface{} `json:"cfr"`
	SampleSize int64       `json:"sample_size"`
}

func (q *Queries) ChangeFailureRateForTeamInWindow(ctx context.Context, arg ChangeFailureRateForTeamInWindowParams) (ChangeFailureRateForTeamInWindowRow, error) {
	row := q.db.QueryRow(ctx, changeFailureRateForTeamInWindow, arg.TeamID, arg.FinishedSince)
	var i ChangeFailureRateForTeamInWindowRow
	err := row.Scan(&i.Cfr, &i.SampleSize)
	return i, err
}

const countSuccessfulProductionDeploymentsForTeamInWindow = `-- name: CountSuccessfulProductionDeploymentsForTeamInWindow :one

SELECT COUNT(*)::bigint AS deploy_count
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
JOIN platform.project p     ON p.id = d.project_id
WHERE p.team_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
`

type CountSuccessfulProductionDeploymentsForTeamInWindowParams struct {
	TeamID        pgtype.UUID        `json:"team_id"`
	FinishedSince pgtype.Timestamptz `json:"finished_since"`
}

// Agregações DORA por time. Todas as queries usam a mesma estratégia:
// expande os projetos do time via subselect em platform.project.team_id e
// aplica a mesma lógica da versão "by project".
//
// Convenção: COALESCE em saídas opcionais (PERCENTILE_CONT/AVG/divisão por 0)
// pra sqlc gerar tipo concreto. Caller decide via sample_size se o valor
// tem significado.
func (q *Queries) CountSuccessfulProductionDeploymentsForTeamInWindow(ctx context.Context, arg CountSuccessfulProductionDeploymentsForTeamInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulProductionDeploymentsForTeamInWindow, arg.TeamID, arg.FinishedSince)
	var deploy_count int64
	err := row.Scan(&deploy_count)
	return deploy_count, err
}

const deploymentsPerDayForTeamInWindow = `-- name: DeploymentsPerDayForTeamInWindow :many
SELECT
  DATE_TRUNC('day', d.finished_at AT TIME ZONE 'UTC')::date AS day,
  COUNT(*)::int AS deploy_count
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
JOIN platform.project p     ON p.id = d.project_id
WHERE p.team_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
GROUP BY 1
ORDER BY 1
`

type DeploymentsPerDayForTeamInWindowParams struct {
	TeamID        pgtype.UUID        `json:"team_id"`
	FinishedSince pgtype.Timestamptz `json:"finished_since"`
}

type DeploymentsPerDayForTeamInWindowRow struct {
	Day         pgtype.Date `json:"day"`
	DeployCount int32       `json:"deploy_count"`
}

func (q *Queries) DeploymentsPerDayForTeamInWindow(ctx context.Context, arg DeploymentsPerDayForTeamInWindowParams) ([]DeploymentsPerDayForTeamInWindowRow, error) {
	rows, err := q.db.Query(ctx, deploymentsPerDayForTeamInWindow, arg.TeamID, arg.FinishedSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentsPerDayForTeamInWindowRow{}
	for rows.Next() {
		var i DeploymentsPerDayForTeamInWindowRow
		if err := rows.Scan(&i.Day, &i.DeployCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leadTimeMedianForTeamInWindow = `-- name: LeadTimeMedianForTeamInWindow :one
SELECT
  COALESCE(
    PERCENTILE_CONT(0.5) WITHIN GROUP (
      ORDER BY EXTRACT(EPOCH FROM (d.finished_at - mr.first_commit_at))
    ),
    0
  ) AS median_seconds,
  COUNT(*) AS sample_size
FROM platform.deployment d
JOIN platform.environment e        ON e.id = d.environment_id
JOIN platform.project p            ON p.id = d.project_id
JOIN platform.deployment_mr_link l ON l.deployment_id = d.id
JOIN platform.merge_request mr     ON mr.id = l.merge_request_id
WHERE p.team_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
  AND mr.first_commit_at IS NOT NULL
  AND NOT mr.author_is_bot
`

type LeadTimeMedianForTeamInWindowParams struct {
	TeamID        pgtype.UUID        `json:"team_id"`
	FinishedSince pgtype.Timestamptz `json:"finished_since"`
}

type LeadTimeMedianForTeamInWindowRow struct {
	MedianSeconds interface{} `json:"median_seconds"`
	SampleSize    int64       `json:"sample_size"`
}

func (q *Queries) LeadTimeMedianForTeamInWindow(ctx context.Context, arg LeadTimeMedianForTeamInWindowParams) (LeadTimeMedianForTeamInWindowRow, error) {
	row := q.db.QueryRow(ctx, leadTimeMedianForTeamInWindow, arg.TeamID, arg.FinishedSince)
	var i LeadTimeMedianForTeamInWindowRow
	err := row.Scan(&i.MedianSeconds, &i.SampleSize)
	return i, err
}

const mTTRMeanSecondsForTeamInWindow = `-- name: MTTRMeanSecondsForTeamInWindow :one
SELECT
  COALESCE(
    AVG(EXTRACT(EPOCH FROM (i.resolved_at - i.created_at))),
    0
  ) AS mean_seconds,
  COUNT(*) AS sample_size
FROM platform.incident i
JOIN platform.project p
  ON p.tenant_id = i.tenant_id
  AND i.jira_project_key = ANY(p.jira_project_keys)
WHERE p.team_id = $1
  AND i.resolved_at IS NOT NULL
  AND i.resolved_at >= $2
`

type MTTRMeanSecondsForTeamInWindowParams struct {
	TeamID        pgtype.UUID        `json:"team_id"`
	ResolvedSince pgtype.Timestamptz `json:"resolved_since"`
}

type MTTRMeanSecondsForTeamInWindowRow struct {
	MeanSeconds interface{} `json:"mean_seconds"`
	SampleSize  int64       `json:"sample_size"`
}

func (q *Queries) MTTRMeanSecondsForTeamInWindow(ctx context.Context, arg MTTRMeanSecondsForTeamInWindowParams) (MTTRMeanSecondsForTeamInWindowRow, error) {
	row := q.db.QueryRow(ctx, mTTRMeanSecondsForTeamInWindow, arg.TeamID, arg.ResolvedSince)
	var i MTTRMeanSecondsForTeamInWindowRow
	err := row.Scan(&i.MeanSeconds, &i.SampleSize)
	return i, err
}
