// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignProjectToTeam = `-- name: AssignProjectToTeam :one
UPDATE platform.project
SET team_id = $1
WHERE id = $2
RETURNING id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at
`

type AssignProjectToTeamParams struct {
	TeamID    pgtype.UUID `json:"team_id"`
	ProjectID uuid.UUID   `json:"project_id"`
}

func (q *Queries) AssignProjectToTeam(ctx context.Context, arg AssignProjectToTeamParams) (PlatformProject, error) {
	row := q.db.QueryRow(ctx, assignProjectToTeam, arg.TeamID, arg.ProjectID)
	var i PlatformProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TeamID,
		&i.SourceInstanceID,
		&i.ExternalID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.ProductionEnvPattern,
		&i.IncidentJql,
		&i.JiraProjectKeys,
		&i.Active,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO platform.team (tenant_id, slug, name, color, emoji)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, slug, name, color, emoji, created_at
`

type CreateTeamParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Slug     string    `json:"slug"`
	Name     string    `json:"name"`
	Color    *string   `json:"color"`
	Emoji    *string   `json:"emoji"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (PlatformTeam, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Color,
		arg.Emoji,
	)
	var i PlatformTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Color,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM platform.team WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, tenant_id, slug, name, color, emoji, created_at FROM platform.team WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (PlatformTeam, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i PlatformTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Color,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectsByTeam = `-- name: ListProjectsByTeam :many
SELECT id, tenant_id, team_id, source_instance_id, external_id, path_with_namespace, default_branch, production_env_pattern, incident_jql, jira_project_keys, active, created_at, last_synced_at FROM platform.project
WHERE team_id = $1
ORDER BY path_with_namespace
`

func (q *Queries) ListProjectsByTeam(ctx context.Context, teamID pgtype.UUID) ([]PlatformProject, error) {
	rows, err := q.db.Query(ctx, listProjectsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformProject{}
	for rows.Next() {
		var i PlatformProject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TeamID,
			&i.SourceInstanceID,
			&i.ExternalID,
			&i.PathWithNamespace,
			&i.DefaultBranch,
			&i.ProductionEnvPattern,
			&i.IncidentJql,
			&i.JiraProjectKeys,
			&i.Active,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByTenant = `-- name: ListTeamsByTenant :many
SELECT id, tenant_id, slug, name, color, emoji, created_at FROM platform.team
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListTeamsByTenant(ctx context.Context, tenantID uuid.UUID) ([]PlatformTeam, error) {
	rows, err := q.db.Query(ctx, listTeamsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformTeam{}
	for rows.Next() {
		var i PlatformTeam
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Color,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE platform.team
SET name  = COALESCE($1, name),
    color = COALESCE($2, color),
    emoji = COALESCE($3, emoji)
WHERE id = $4
RETURNING id, tenant_id, slug, name, color, emoji, created_at
`

type UpdateTeamParams struct {
	Name  *string   `json:"name"`
	Color *string   `json:"color"`
	Emoji *string   `json:"emoji"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (PlatformTeam, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.Color,
		arg.Emoji,
		arg.ID,
	)
	var i PlatformTeam
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Color,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}
