// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeseries.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deploymentsPerDayInWindow = `-- name: DeploymentsPerDayInWindow :many
SELECT
  DATE_TRUNC('day', d.finished_at AT TIME ZONE 'UTC')::date AS day,
  COUNT(*)::int AS deploy_count
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
WHERE d.project_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
GROUP BY 1
ORDER BY 1
`

type DeploymentsPerDayInWindowParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	FinishedSince pgtype.Timestamptz `json:"finished_since"`
}

type DeploymentsPerDayInWindowRow struct {
	Day         pgtype.Date `json:"day"`
	DeployCount int32       `json:"deploy_count"`
}

// Série temporal de deployments de produção bem-sucedidos por dia (UTC).
// Drive da curva de Deployment Frequency.
func (q *Queries) DeploymentsPerDayInWindow(ctx context.Context, arg DeploymentsPerDayInWindowParams) ([]DeploymentsPerDayInWindowRow, error) {
	rows, err := q.db.Query(ctx, deploymentsPerDayInWindow, arg.ProjectID, arg.FinishedSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentsPerDayInWindowRow{}
	for rows.Next() {
		var i DeploymentsPerDayInWindowRow
		if err := rows.Scan(&i.Day, &i.DeployCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionDeploymentsInWindow = `-- name: ListProductionDeploymentsInWindow :many
SELECT
  d.id,
  d.sha,
  d.ref,
  d.status,
  d.triggered_by,
  d.started_at,
  d.finished_at,
  e.name AS environment_name
FROM platform.deployment d
JOIN platform.environment e ON e.id = d.environment_id
WHERE d.project_id = $1
  AND e.is_production
  AND d.status = 'success'
  AND d.finished_at >= $2
ORDER BY d.finished_at DESC
`

type ListProductionDeploymentsInWindowParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	FinishedSince pgtype.Timestamptz `json:"finished_since"`
}

type ListProductionDeploymentsInWindowRow struct {
	ID              uuid.UUID          `json:"id"`
	Sha             string             `json:"sha"`
	Ref             *string            `json:"ref"`
	Status          string             `json:"status"`
	TriggeredBy     *string            `json:"triggered_by"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	EnvironmentName string             `json:"environment_name"`
}

// Lista bruta dos deploys de produção na janela. Drive do drill-down
// "clique no tile/ponto → ver os deploys que compõem".
func (q *Queries) ListProductionDeploymentsInWindow(ctx context.Context, arg ListProductionDeploymentsInWindowParams) ([]ListProductionDeploymentsInWindowRow, error) {
	rows, err := q.db.Query(ctx, listProductionDeploymentsInWindow, arg.ProjectID, arg.FinishedSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionDeploymentsInWindowRow{}
	for rows.Next() {
		var i ListProductionDeploymentsInWindowRow
		if err := rows.Scan(
			&i.ID,
			&i.Sha,
			&i.Ref,
			&i.Status,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
