server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback — Angular Router controla as rotas no client.
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Cache agressivo de assets com hash.
  location ~* \.(js|css|woff2?|ttf|eot|svg|png|jpg|jpeg|gif|ico)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # Sem cache para o HTML (atualiza referência aos assets hashados).
  location = /index.html {
    add_header Cache-Control "no-store";
  }
}
